### ISSUE TITLE
Resolver nome da currency try - key word Java

### ISSUE THREAD

**Issue by SusanaSousa** [ishouldbedany/ConverteurC#12]
Uma das currencies tem o nome de uma keyword java. Isto está a impedir que o respectivo drawable seja chamado.

**Comment by ishouldbedany** [comment]
Também me aconteceu isto. A melhor maneira é mudar o nome do ficheiro para "tryy.png" e o código para "tryy". E, no construtor de Currency, lidar com o caso em que o código é "tryy".

**Comment by SusanaSousa** [comment]
ahah eu resolvi colocando ttry. Temos de uniformizar
