### ISSUE TITLE
Ícones da Action Bar e Tabs desfocados

### ISSUE THREAD

**Issue by ishouldbedany** [ishouldbedany/ConverteurC#8]
No meu telemóvel, que provavelmente tem uma resolução diferente, os ícones da ActionBar e nas Tabs aparecem desfocados. Acho que a melhor solução é [fornecer todos os nossos ícones como vectores](https://developer.android.com/studio/write/vector-asset-studio.html).

**Comment by ishouldbedany** [comment]
Pic ilustrativa
![screenshot_20171111-001756](https://user-images.githubusercontent.com/6266595/32683807-3c43fd34-c676-11e7-9697-86e2a9533913.png)

**Comment by SusanaSousa** [comment]
Humm... Não tinha reparado nisso no meu telemóvel. Okay. Vou ter isso em atenção

**Comment by ishouldbedany** [comment]
Já resolvi, na minha versão
